<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>75d257d2-62b7-4422-bf86-0bdd92a06ec8</UserSecretsId>
  </PropertyGroup>

  
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\GerenciamentoDeBar.Aplicacao\GerenciamentoDeBar.Aplicacao.csproj" />
    <ProjectReference Include="..\GerenciamentoDeBar.Dominio\GerenciamentoDeBar.Dominio.csproj" />
    <ProjectReference Include="..\GerenciamentoDeBar.Infra\GerenciamentoDeBar.Infra.csproj" />
  </ItemGroup>


</Project>
